# Generated by Django 3.2.7 on 2021-09-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipsytequilaapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
    ]
