# Generated by Django 3.2.7 on 2021-09-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipsytequilaapi', '0002_auto_20210917_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='rating',
        ),
    ]
